#!/usr/bin/env python

import sys
import importlib

# Nuclex SCons libraries
sys.path.append('../../addons/scripts/scons')
nuclex = importlib.import_module('nuclex')

# ----------------------------------------------------------------------------------------------- #

environment = nuclex.create_blender_environment()

environment.export_collada(
    './Models/Ramp.dae', # Output file name
    './Models/Ramp.blend', # Blender input file
    [ 'Ramp' ] # Meshes to export
)

environment.export_collada(
    './Models/Staircase.dae', # Output file name
    './Models/Staircase.blend', # Blender input file
    [ 'Staircase' ] # Meshes to export
)

environment.export_collada(
    './Models/Bump.dae', # Output file name
    './Models/Bump.blend', # Blender input file
    [ 'Bump' ] # Meshes to export
)

# ----------------------------------------------------------------------------------------------- #

#AlwaysBuild(export)
