#!/usr/bin/env python

import sys
import importlib

# Nuclex SCons libraries
sys.path.append('../../../addons/scripts/scons')
nuclex = importlib.import_module('nuclex')

# ----------------------------------------------------------------------------------------------- #

environment = nuclex.create_blender_environment()

environment.export_collada(
    './Models/Dummy.dae',
    './Models/Dummy.Rigify.blend',
    [
        'rig',
        'Body'
    ]
)

# ----------------------------------------------------------------------------------------------- #

#AlwaysBuild(export)
